
# utils/pdf_export.py

from fpdf import FPDF
import datetime


class ClientMemo(FPDF):
    def header(self):
        self.set_font("Arial", "B", 14)
        self.set_text_color(31, 58, 95)
        self.cell(0, 10, "Tax Intelligence Platform -- Client Analysis Memo", ln=True, align="C")
        self.set_font("Arial", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, f"Generated: {datetime.datetime.now().strftime('%B %d, %Y at %I:%M %p')}", ln=True, align="C")
        self.ln(4)
        self.set_draw_color(31, 58, 95)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "CONFIDENTIAL -- For authorized use only. This analysis is based on client-provided data and IRS published guidelines.", align="C")

    def section_title(self, title):
        self.set_font("Arial", "B", 12)
        self.set_text_color(31, 58, 95)
        self.cell(0, 8, title, ln=True)
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def body_line(self, label, value):
        self.set_font("Arial", "B", 10)
        self.set_text_color(50, 50, 50)
        self.cell(90, 7, label, border=0)
        self.set_font("Arial", "", 10)
        self.cell(0, 7, str(value), ln=True)

    def advisory(self, text):
        self.set_font("Arial", "I", 10)
        self.set_text_color(80, 80, 80)
        self.multi_cell(0, 6, text)
        self.ln(2)


def generate_pdf(client_data: dict, output_path: str):
    pdf = ClientMemo()
    pdf.add_page()

    pdf.section_title("Client Profile")
    pdf.body_line("Filing Status:", client_data["filing_status"].replace("_", " ").title())
    pdf.body_line("Adjusted Gross Income:", f"${client_data['agi']:,.2f}")
    pdf.body_line("Number of Qualifying Children:", str(client_data["num_children"]))
    pdf.ln(4)

    pdf.section_title("Module 1 -- Return Optimization")
    pdf.body_line("Deduction Strategy:", client_data.get("deduction_choice", "N/A"))
    pdf.body_line("Optimal Deduction Amount:", f"${client_data.get('optimal_deduction', 0):,.2f}")
    pdf.body_line("Taxable Income:", f"${client_data.get('taxable_income', 0):,.2f}")
    pdf.body_line("Gross Federal Tax:", f"${client_data.get('gross_federal_tax', 0):,.2f}")
    pdf.body_line("Total Credits Applied:", f"-${client_data.get('total_credits', 0):,.2f}")
    pdf.body_line("Net Federal Tax Liability (2024):", f"${client_data.get('net_tax_2024', 0):,.2f}")
    credits = client_data.get("credits_identified", {})
    if credits:
        pdf.ln(2)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(0, 7, "Credits Identified:", ln=True)
        for k, v in credits.items():
            pdf.body_line(f"  {k}:", f"${v:,.2f}")
    pdf.ln(4)

    pdf.section_title("Module 2 -- Audit Risk Assessment")
    pdf.body_line("Audit Risk Score:", f"{client_data.get('audit_risk_score', 0)} / 100")
    pdf.body_line("Risk Level:", client_data.get("audit_risk_level", "N/A"))
    pdf.advisory(client_data.get("audit_recommendation", ""))
    risk_factors = client_data.get("audit_risk_factors", {})
    if risk_factors:
        pdf.set_font("Arial", "B", 10)
        pdf.cell(0, 7, "Contributing Risk Factors:", ln=True)
        for factor in risk_factors:
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 6, f"  - {factor}", ln=True)
    pdf.ln(4)

    pdf.section_title("Module 3 -- TCJA Sunset Projection")
    pdf.body_line("2025 Net Federal Tax (Current Law):", f"${client_data.get('net_tax_2025', 0):,.2f}")
    pdf.body_line("2026 Projected Net Tax (Sunset Law):", f"${client_data.get('net_tax_2026_sunset', 0):,.2f}")
    pdf.body_line("Projected Dollar Increase:", f"${client_data.get('tcja_delta', 0):,.2f}")
    pdf.body_line("Percentage Change:", f"{client_data.get('tcja_pct_change', 0):.1f}%")
    pdf.ln(4)

    pdf.section_title("Analyst Notes")
    pdf.advisory(
        "This memo was generated by the Tax Intelligence Platform using client-provided inputs and "
        "IRS-published 2024 tax parameters. All figures are estimates intended for planning purposes only "
        "and do not constitute a filed return or formal tax opinion. Final figures should be verified "
        "by a licensed CPA prior to submission."
    )

    pdf.output(output_path)
    return output_path
